# ------------------------
# Database (Docker / Prod)
# ------------------------
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/orderdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.pool-name=OrderHikariCP

# ------------------------
# JPA / Hibernate
# ------------------------
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ------------------------
# Logging (clean en prod)
# ------------------------
logging.level.root=INFO
logging.level.com.ecommerce=INFO
logging.level.org.springframework.security=WARN